# Generated by Django 4.1.5 on 2023-03-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soil_moisture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flower_1', models.FloatField(max_length=80)),
                ('flower_2', models.FloatField(max_length=80)),
                ('flower_3', models.FloatField(max_length=80)),
            ],
        ),
    ]
