# Generated by Django 4.1.5 on 2023-04-01 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_soil_moisture_measurement_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Soil_moisture',
            new_name='Flowers_data',
        ),
    ]
