# Generated by Django 4.2.1 on 2023-07-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_flowers_data_brightness'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_date', models.DateTimeField()),
                ('brightness', models.FloatField(max_length=80)),
                ('temperature', models.FloatField(max_length=80)),
                ('humidity', models.FloatField(max_length=80)),
                ('pressure', models.FloatField(max_length=80)),
                ('voc', models.IntegerField(max_length=80)),
            ],
        ),
        migrations.RemoveField(
            model_name='flowers_data',
            name='brightness',
        ),
    ]
